#!/usr/bin/env bash
# Init script to manage manage_my_process

case "$1" in
    start)
        ./manage_my_process > /dev/null 2>&1 &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        ./manage_my_process > /dev/null 2>&1 &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
